# Generated by Django 3.2.5 on 2021-07-07 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20210707_1345'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Followings',
            new_name='Follow',
        ),
    ]
